# Generated by Django 5.1.3 on 2024-11-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='c_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='q_text',
        ),
    ]
